services:
  - type: web
    name: learnoverse
    env: node
    plan: free
    buildCommand: npm ci && npm run build && cd backend && npm install && npm run build
    startCommand: cd backend && npm start
